[package]
name = "nmallocator"
version = "0.1.0"
edition = "2021"
description = "Novusk Memory Allocator"

[dependencies]
wee_alloc = { version = "0.4.5", features = ["static_array_backend"] }

[features]
wee_allocator = []
