[package]
name = "init"
version = "0.1.0"
authors = ["NathanMcMillan54 <nathanmcmillan54@gmail.com>"]
edition = "2018"

[dependencies]
drivers = { path = "../drivers/" }
fs = { path = "../fs/" }
include = { path = "../include/" }
kernel = { path = "../kernel/" }
# Modules
m1 = { path = "../kernel/modules/m1/" }
