[package]
name = "init"
version = "0.1.0"
authors = ["NathanMcMillan54 <nathanmcmillan54@gmail.com>"]
edition = "2018"


[dependencies]
drivers = { path = "../drivers/" }
include = { path = "../include/" }
kernel = { path = "../kernel/" }
modules = { path = "../kernel/modules/" }
