[package]
name = "novusk"
version = "2.1.3"
authors = ["Nathan McMillan <nathanmcmillan54@gmail.com>"]
edition = "2018"

[workspace]
members = [
    # Architectures
    "arch/x86/",
    # Drivers
    "drivers/nkuefi/",
]

[target.'cfg(target_arch = "x86_64")'.dependencies]
bootloader = "0.9.12"
nkuefi = { path = "drivers/nkuefi/" }
x86 = { path = "arch/x86/" }
