[package]
name = "novusk"
version = "1.1.0"
authors = ["Nathan McMillan <nathanmcmillan54@gmail.com>"]
edition = "2018"

[lib]
name = "novusk"
edition = "2018"
path = "src/lib.rs"
crate-type = ["staticlib"]

[workspace]
members = [
    "tools/build/",
    "arch/x86_64/",
    "include/",
    "init/",
    "kernel/",
    "kernel/modules/"
]

[dependencies]
include = { path = "include/" }
init = { path = "init/" }
kernel = { path = "kernel/" }
modules = { path = "kernel/modules/" }
x86_64 = { path = "arch/x86_64/" }
