[package]
name = "novusk"
version = "2.1.3"
authors = ["Nathan McMillan <nathanmcmillan54@gmail.com>"]
edition = "2018"

[workspace]
members = [
    # Architectures
    "arch/x86/",
    # Drivers
    "drivers/gpu/",
    "drivers/nkuefi/",
    # GPUs
    # Kernel
    "kernel/kinfo/",
    "kernel/printk/",
    # Libraries
    "lib/libcolor/",
]

[target.'cfg(target_arch = "x86_64")'.dependencies]
bootloader = "0.9.12"
x86 = { path = "arch/x86/" }

[target.'cfg(target_arch = "x86")'.dependencies]
x86 = { path = "arch/x86/" }

[dependencies]
register = { version = "1.0.2", optional = true }

[features]
default = []
bios_boot = ["register"]
uefi_boot = ["register"]
