[package]
name = "novusk"
version = "1.2.0"
authors = ["Nathan McMillan <nathanmcmillan54@gmail.com>"]
edition = "2018"

[[bin]]
name = "novusk_kernel"
edition = "2018"
path = "src/main.rs"

[lib]
name = "novusk"
edition = "2018"
path = "src/lib.rs"

[workspace]
members = [
    "arch/aarch64/",
    "arch/x86/",
]

[dependencies]
aarch64 = { path = "arch/aarch64/" }
x86 = { path = "arch/x86/" }
