[package]
name = "novusk"
version = "1.1.0"
authors = ["Nathan McMillan <nathanmcmillan54@gmail.com>"]
edition = "2018"

[lib]
name = "novusk"
edition = "2018"
path = "src/lib.rs"
crate-type = ["staticlib"]

[workspace]
members = [
    "tools/build/",
    "arch/x86_64/",
]

[dependencies]
x86_64 = { path = "arch/x86_64/" }
