[package]
name = "novusk"
version = "1.1.0"
authors = ["NathanMcMillan54 <nathanmcmillan54@gmail.com>"]
edition = "2018"

[lib]
name = "novusk"
edition = "2018"
path = "src/lib.rs"
crate-type = ["staticlib"]
