[package]
name = "novusk"
version = "1.1.0"
authors = ["Nathan McMillan <nathanmcmillan54@gmail.com>"]
edition = "2018"

[[bin]]
name = "novusk_kernel"
edition = "2018"
path = "src/main.rs"

[lib]
name = "novusk"
edition = "2018"
path = "src/lib.rs"

[workspace]
members = [
    "arch/arm/",
    "arch/x86_64/",
    "drivers/",
    "kernel/",
    "tools/build/",
]

[target.'cfg(target_arch = "x86_64")'.dependencies]
bootloader = "0.9.12"
x86_64 = { path = "arch/x86_64/" }

[target.'cfg(target_arch = "arm")'.dependencies]
arm = { path = "arch/arm/" }

[dependencies]
drivers = { path = "drivers/" }
kernel = { path = "kernel/" }
