[package]
name = "novusk"
version = "1.0.0"
authors = ["NathanMcMillan54 <nathanmcmillan54@gmail.com>"]
edition = "2018"

[workspace]
members = [
    "arch/",
]

[dependencies]
arch = { path = "arch/" }
bootloader = "0.9.11"
