[package]
name = "novusk"
version = "1.1.0"
authors = ["Nathan McMillan <nathanmcmillan54@gmail.com>"]
edition = "2018"

[[bin]]
name = "novusk_kernel"
edition = "2018"
path = "src/main.rs"

[lib]
name = "novusk"
edition = "2018"
path = "src/lib.rs"

[workspace]
members = [
    "arch/x86_64/",
    "drivers/",
    "include/",
    "init/",
    "kernel/",
    # Modules
    "kernel/modules/ex1/",
    # Tools
    "tools/build/",
]

[target.'cfg(target_arch = "x86_64")'.dependencies]
bootloader = "0.9.12"
x86_64 = { path = "arch/x86_64/" }


[dependencies]
drivers = { path = "drivers/" }
include = { path = "include/" }
init = { path = "init/" }
kernel = { path = "kernel/" }
