[package]
name = "novusk"
version = "0.1.0"
authors = ["Nathan McMillan <nathanmcmillan54@gmail.com>"]
edition = "2018"

[workspace]
members = [
    # Architectures
    "arch/x86/",
    # Drivers
    "drivers/nkuefi/",
    # Libraries
    "lib/libcolor/",
]

[dependencies]
bootloader = "0.9.12"
register = { version = "1.0.2", optional = true }
x86 = { path = "arch/x86/" }
