[package]
name = "novusk"
version = "1.2.0"
authors = ["Nathan McMillan <nathanmcmillan54@gmail.com>"]
edition = "2018"

[[bin]]
name = "novusk_kernel"
edition = "2018"
path = "src/main.rs"

[lib]
name = "novusk"
edition = "2018"
path = "src/lib.rs"

[workspace]
members = [
    "arch/aarch64/",
    "arch/x86_64/",
    "drivers/",
    "fs/",
    "include/",
    "init/",
    "kernel/",
    "mm/",
    # Modules
    "kernel/modules/ex1/",
    "kernel/modules/m1/",
    # Tools
    "tools/build/",
    # Example
    "example/",
]

[target.'cfg(target_arch = "x86_64")'.dependencies]
bootloader = "0.9.12"

[dependencies]
# Architectures
aarch64 = { path = "arch/aarch64/" }
x86_64 = { path = "arch/x86_64/" }
# Kernel
drivers = { path = "drivers/" }
fs = { path = "fs/" }
include = { path = "include/" }
init = { path = "init/" }
kernel = { path = "kernel/" }
libn = { git = "https://github.com/new-kernel/libn/" }
mm = { path = "mm/" }
