[package]
name = "xtensa"
version = "0.1.0"
authors = ["Nathan McMillan <nathanmcmillan54@gmail.com>"]
edition = "2018"

[lib]
name = "xtensa_novusk"
edition = "2018"
path = "src/lib.rs"

[workspace]
members = [
    "esp32/",
]

[dependencies]
# Dependencies
esp32-hal = "0.2.0"
# Boards
esp32 = { path = "esp32/" }
# Drivers
esp32_fw = { path = "../../drivers/firmware/esp32_fw/" }
net = { path = "../../drivers/net/" }

register = { version = "1.x.x", optional = true }


[features]
default = []
esp32_board = ["register"]
