[package]
name = "armfb"
version = "0.1.0"
edition = "2021"
description = "ARM 32/64 bit frambuffer graphics"

[target.'cfg(target_arch = "aarch64")'.dependencies]
rpi = { path = "../../rpi/" }

[dependencies]
fb = { path = "../../fb/" }
libcolor = { path = "../../../lib/libcolor/" }
novuskinc = "0.1.0"
