[package]
name = "esp32_fw"
version = "0.1.0"
authors = ["Nathan McMillan <nathanmcmillan54@gmail.com>"]
edition = "2018"
description = "Firmware drivers for esp32 board"

[dependencies]
esp32-hal = "0.2.0"
