[package]
name = "gpu"
version = "0.1.0"
edition = "2018"
description = "GPU initialization"

[dependencies]
gop = { path = "../../gpu/gop/" }
macros = { path = "../../kernel/macros/" }
vga = { path = "../../gpu/vga/" }
