[package]
name = "dif"
version = "0.1.0"
edition = "2021"
description = "A library for reading DIF files."

[dependencies]

[build-dependencies]
cc = "1.0.72"
ccbuild = { path = "../../tools/build/ccbuild/" }
