[package]
name = "riscv"
version = "0.1.0"
edition = "2018"
description = "RISCV32/64 kernel support"

[target.'cfg(target_arch = "riscv32")'.dependencies]
hifived = { path = "../../drivers/firmware/riscv/hifived/" }

[target.'cfg(target_arch = "riscv64")'.dependencies]
mio = { path = "../../mm/mio/" }

[dependencies]
device = { path = "../../drivers/firmware/device/" }
kinfo = { path = "../../kernel/kinfo/" }
libbmu = { path = "../../lib/libbmu/" }
modules = { path = "../../kernel/modules/" }
novuskinc = { path = "../../include/novusk/" }
r0 = "1.0.0"
risc-v = "0.0.0"
riscv-rt = "0.8.0"

[features]
virt = []
hifive = ["no-mem"]
no-mem = []
