[package]
name = "riscv"
version = "0.1.0"
edition = "2021"
description = "Support for RISCV32/64"

[dependencies]
nmallocator = { path = "../../mm/nmallocator/", features = ["wee_allocator"] }
r0 = "1.0.0"
riscv-rt = "0.8.0"
setup = { path = "../../kernel/setup/" }
sifive = { path = "../../drivers/firmware/sifive/" }

[features]
hifive = ["sifive/hifive"]
lofive = ["sifive/lofive"]
virt = []
