[package]
name = "riscv"
version = "0.1.0"
edition = "2018"
description = "RISCV32/64 support"

[target.'cfg(target_arch = "riscv32")'.dependencies]
hifive1 = { version = "0.9.0", features = ["board-hifive1"] }

[dependencies]
nmallocator = { path = "../../mm/nmallocator/" }

[features]
default = []
hifive = []
sifive = []
virt = []
