[package]
name = "riscv"
version = "0.1.0"
edition = "2018"
description = "RISCV32/64 support"

[target.'cfg(target_arch = "riscv32")'.dependencies]
sifive = { path = "../../drivers/firmware/sifive/" }

[dependencies]
nmallocator = { path = "../../mm/nmallocator/" }
riscv-rt = "0.8.0"

[features]
default = []
hifive = ["sifive/hifive"]
lofive = ["sifive/lofive"]
virt = []
