[package]
name = "stmd"
version = "0.1.0"
edition = "2021"
description = "Support for STM32 boards"

[dependencies]
ethernet = { path = "../../../../drivers/net/ethernet/" }
kinfo = { path = "../../../../kernel/kinfo/" }
novuskinc = { path = "../../../../include/novusk/" }
stm_eth = { path = "../../../../net/ethernet/stm_eth/" }
stm32f4xx-hal = "0.10.0"

[features]
stm32f401 = ["stm32f4xx-hal/stm32f401", "stm_eth/unsupported_stm32fxxx"]
stm32f407 = ["stm32f4xx-hal/stm32f407", "stm_eth/stm32f407"]
qemu = []
