[package]
name = "stmd"
version = "0.1.0"
edition = "2018"
description = "Support for STM32 boards"

[dependencies]
novuskinc = { path = "../../../../include/novusk/" }
stm32f4xx-hal = "0.10.0"

[features]
stm32f401 = ["stm32f4xx-hal/stm32f401"]
