[package]
name = "net"
version = "0.1.0"
authors = ["Nathan McMillan <nathanmcmillan54@gmail.com>"]
edition = "2018"
description = "Network driver initialization"

[dependencies]
# Kernel
kerror = { path = "../../kernel/kerror/" }
# Net drivers
esp32net = { path = "../../net/esp32/" }