[package]
name = "arm32"
version = "0.1.0"
edition = "2018"
description = "arm32 and some Aarch64 support"

[dependencies]
cortex-m-rt = "0.6.10"
net = { path = "../../drivers/net/" }
stm32f4xx-hal = {version = "0.8.3", optional = true}
