[package]
name = "arm32"
version = "0.1.0"
edition = "2018"
description = "ARM32 and some Aarch64 kernel support"

[dependencies]
alloc-cortex-m = "0.4.1"
cortex-m-rt = "0.7.0"
cortex-m-rt-macros = "0.7.0"
cortex-m-semihosting = "0.3.7"
lazy_static = "1.4.0"
spin = "0.9.2"
stellarisd = { path = "../../drivers/firmware/arm/stellarisd/" }

[features]
default = []
cortex_a = []
cortex_m = []
stellaris_6965 = ["cortex_m"]
