[package]
name = "stm"
version = "0.1.0"
edition = "2021"
description = "Support for ST devices, mainly STM32 boards"

[lib]
crate-type = ["staticlib"]

[dependencies]
novuskinc = { path = "../../../include/novusk/" }

[build-dependencies]
difi = { path = "../../../tools/build/difi/" }
