[package]
name = "vgag"
version = "0.1.0"
edition = "2021"
description = "Vga graphics driver"

[dependencies]
libcolor = { path = "../../../lib/libcolor/" }
novuskinc = { path = "../../../include/novusk/", features = ["library"] }
printk = { path = "../../../kernel/printk/" }
volatile = "0.2.7"

[features]
default = []
no_panic = []
