[package]
name = "vgag"
version = "0.1.0"
edition = "2021"
description = "Vga graphics driver"

[lib]
#crate-type = ["staticlib",]

[dependencies]
novuskinc = { path = "../../../include/novusk/", features = ["library"] }
vga = "0.2.7"
