[package]
name = "vgag"
version = "0.1.0"
edition = "2021"
description = "Vga graphics driver"

[dependencies]
novuskinc = { path = "../../../include/novusk/", features = ["library"] }

[features]
default = []
no_panic = []
