[package]
name = "vgag"
version = "0.1.0"
edition = "2021"
description = "Vga graphics driver"

[dependencies]
fb = { path = "../../fb/" }
lazy_static = "1.4.0"
novuskinc = "0.1.0"
spin = "0.9.2"
vga = "0.2.7"
