[package]
name = "rpi"
version = "0.1.0"
edition = "2018"
description = ""

[dependencies]
device = { path = "../device/" }
mio = { path = "../../mm/mio/" }
kinfo = { path = "../../kernel/kinfo/" }
libcolor = { path = "../../lib/libcolor/" }
libbmu = { path = "../../lib/libbmu/" }
printk = { path = "../../kernel/printk/" }
tock-registers = "0.7.0"
