[package]
name = "x86"
version = "0.1.0"
authors = ["Nathan McMillan <nathanmcmillan54@gmail.com>"]
edition = "2018"

[dependencies]
rlibc = "1.0.0"

[dependencies.uefi]
version = "0.8.0"
features = ['default']

[build-dependencies]
build = { path = "../../tools/build/" }
