[package]
name = "x86"
version = "0.1.0"
edition = "2018"

[workspace]
members = [
    # Tools
    "disk_img",
]

[dependencies]
# Dependencies
uefi = "0.8.0"
uefi-macros = "0.3.3"
# Drivers
i686 = { path = "../../drivers/i686/" }
uefi_kd = { path = "../../drivers/uefi_kd" }
