[package]
name = "x86"
version = "0.1.0"
authors = ["Nathan McMillan <nathanmcmillan54@gmail.com>"]
edition = "2018"

[lib]
name = "x86"
edition = "2018"
path = "src/lib.rs"
crate-type = ["staticlib"]


[dependencies]

[build-dependencies]
build = { path = "../../tools/build/" }
