[package]
name = "x86"
version = "0.1.0"
authors = ["Nathan McMillan <nathanmcmillan54@gmail.com>"]
edition = "2018"

[lib]
name = "x86_novusk"
path = "src/lib.rs"
edition = "2018"

[dependencies]
# Dependencies
libnu = { git = "https://github.com/new-kernel/libnu/" }
log = { version = "0.4.11", default-features = false }
rlibc = "1.0.0"
uefi = "0.8.1"
uefi-macros = "0.3.3"
uefi-services = "0.5.0"
# Drivers
cpu = { path = "../../drivers/cpu/" }
i686 = { path = "../../drivers/i686/" }
gop = { path = "../../gpu/gop/" }
uefi_kd = { path = "../../drivers/uefi_kd" }
# Include
ctypes = { path = "../../include/ctypes/" }
time = { path = "../../include/time/" }
novusk = { path = "../../include/novusk/" }
# Kernel
init = { path = "../../init/" }
kerror = { path = "../../kernel/kerror/" }
kinfo = { path = "../../kernel/kinfo/" }
printk = { path = "../../kernel/printk/" }
userspace = { path = "../../kernel/userspace/" }
# Libraries
libn = { path = "../../lib/libn/" }
# Modules

# Features
register = { version = "1.x.x", optional = true }

[target.'cfg(target_arch = "x86_64")'.dependencies]
ex1 = { path = "../../kernel/modules/ex1/" }
raw-cpuid = "9.0.0"

[features]
default = []
default_machine = ["register"]
