[package]
name = "x86"
version = "0.1.0"
edition = "2018"
description = "x86 family support for Novusk"

[target.'cfg(target_arch = "x86_64")'.dependencies]
raw-cpuid = "9.0.0"

[dependencies]
gpu = { path = "../../drivers/gpu/" }
kinfo = { path = "../../kernel/kinfo/" }
libcolor = { path = "../../lib/libcolor/" }
nkuefi = { path = "../../drivers/nkuefi/" }
volatile = "0.2.6"
