[package]
name = "x86"
version = "0.1.0"
authors = ["Nathan McMillan <nathanmcmillan54@gmail.com>"]
edition = "2018"

[lib]
name = "x86_novusk"
path = "src/lib.rs"
edition = "2018"

[dependencies]
# Dependencies
log = { version = "0.4.14", default-features = false }
rlibc = "1.0.0"
uefi = "0.8.0"
uefi-macros = "0.3.3"
uefi-services = "0.5.0"
# Drivers
i686 = { path = "../../drivers/i686/" }
uefi_kd = { path = "../../drivers/uefi_kd" }
# Kernel
kernel = { path = "../../kernel/" }
# Features
register = { version = "1.x.x", optional = true }

[features]
default = []
default_machine = ["register"]
