[package]
name = "arm"
version = "0.1.0"
edition = "2021"
description = "ARM kernel support"

[lib]
name = "arm_kernel_lib"
path = "src/lib.rs"
crate-type = ["staticlib"]
edition = "2021"

[[bin]]
name = "arm_kernel_bin"
path = "src/main.rs"
edition = "2021"

[target.'cfg(target_arch = "arm")'.dependencies]
cortex-m-rt = "0.7.1"
cortex-m-semihosting = "0.3.7"
hio = { path = "../../drivers/platform/arm/hio/" }

[dependencies]
cfg-if = "1.0.0"
cortex-a = "6.1.0"
cpu = { path = "../../drivers/cpu/" }
device = { path = "../../drivers/device/" }
dif = { path = "../../include/dif/" }
kinfo = { path = "../../kernel/kinfo/" }
nmallocator = { path = "../../mm/nmallocator/", features = ["wee_allocator"] }
novuskinc = { path = "../../include/novusk/", features = ["library"] }
r0 = "1.0.0"
rlibc = "1.0.0"
setup = { path = "../../kernel/setup/" }
soc = { path = "../../drivers/soc/" }

[features]
default = []
cortex_a = ["nmallocator/wee_allocator"]
cortex_m = ["nmallocator/linked_list"]
rpi3b = ["cortex_a"]
rpi4b = ["cortex_a"]
stellaris6965 = ["cortex_m"]

unknown_soc = []
bcm28xx = []
