[package]
name = "arm"
version = "0.1.0"
edition = "2021"
description = "ARM kernel support"

[lib]
name = "arm_kernel_lib"
path = "src/lib.rs"
crate-type = ["staticlib"]
edition = "2021"

[[bin]]
name = "arm_kernel_bin"
path = "src/main.rs"
edition = "2021"

[dependencies]
cfg-if = "1.0.0"
cortex-a = "6.1.0"
cortex-m = "0.7.3"
cortex-m-rt = "^0.6.15"
cortex-m-semihosting = "0.3.7"
cpu = { path = "../../drivers/cpu/" }
device = { path = "../../drivers/device/" }
kinfo = { path = "../../kernel/kinfo/" }
nmallocator = { path = "../../mm/nmallocator/" }
rlibc = "1.0.0"
setup = { path = "../../kernel/setup/" }

[features]
cortex_a = ["nmallocator/wee_allocator"]
cortex_m = ["nmallocator/linked_list"]
rpi2 = ["cortex_a"]
stellaris_6965 = ["cortex_m"]
