[package]
name = "m1"
version = "0.1.0"
authors = ["Nathan McMillan <nathanmcmillan54@gmail.com>"]
edition = "2018"
description = "Gets kernel, os, and device info. Starts some device drivers"


[dependencies]
kernel = { path = "../../../kernel/" }
