[package]
name = "sys"
version = "0.1.0"
authors = ["Nathan McMillan <nathanmcmillan54@gmail.com>"]
edition = "2018"

[dependencies]
libefi = { path = "../../lib/libefi/" }
printk = { path = "../printk/" }
uefi = "0.8.1"
