[package]
name = "x86_64"
version = "0.1.0"
authors = ["NathanMcMillan54 <nathanmcmillan54@gmail.com>"]
edition = "2018"

[dependencies]
kernel = { path = "../../kernel/" }
volatile = "0.1.0"
spin = "0.4.5"

[build-dependencies]
build = { path = "../../tools/build/" }
