[package]
name = "x86_64"
version = "0.1.0"
edition = "2021"
description = "x86_64 support for Novusk"

[lib]
name = "x86_64_kernel_lib"
edition = "2021"
path = "src/lib.rs"

[[bin]]
name = "x86_64_kernel"
edition = "2021"
path = "src/main.rs"

[dependencies]

[features]
