[package]
name = "x86_64"
version = "0.1.0"
authors = ["NathanMcMillan <nathanmcmillan54@gmail.com>"]
edition = "2018"

[dependencies]
drivers = { path = "../../drivers/" }
kernel = { path = "../../kernel/" }
raw-cpuid = "9.0.0"

[build-dependencies]
build = { path = "../../tools/build/" }
