[package]
name = "x86_64"
version = "0.1.0"
authors = ["NathanMcMillan <nathanmcmillan54@gmail.com>"]
edition = "2018"

[dependencies]
# Novusk
drivers = { path = "../../drivers/" }
include = { path = "../../include/" }
kernel = { path = "../../kernel/" }
libn = { git = "https://github.com/new-kernel/libn/" }
# Modules
ex1 = { path = "../../kernel/modules/ex1/" }
# Dependencies

[build-dependencies]
build = { path = "../../tools/build/" }
