[package]
name = "bcm"
version = "0.1.0"
edition = "2021"
description = "An SOC driver for Broadcom CPUs, currently intended for BCM2837"

[dependencies]
novuskinc = { path = "../../../include/novusk/" }
soc = { path = "../" }
