[package]
name = "ex1"
version = "0.1.0"
authors = ["Nathan McMillan <nathanmcmillan54@gmail.com>"]
edition = "2018"
description = "Example module for x86 Novusk"

[dependencies]
novusk = { path = "../../../include/novusk/" }

[build-dependencies]
cc = "1.0.67"