[package]
name = "stellaris"
version = "0.1.0"
edition = "2021"
description = "A driver for Stellaris devices"

[dependencies]
novuskinc = { path = "../../../include/novusk/" }

[lib]
crate-type = ["staticlib"]
