[package]
name = "ps2_keyboard"
version = "0.1.0"
authors = ["Nathan McMillan <nathanmcmillan54@gmail.com>"]
edition = "2018"

[dependencies]
pc-keyboard = "0.5.1"
printk = { path = "../../../../kernel/printk/" }
