[package]
name = "blue"
version = "0.1.0"
authors = ["Nathan McMillan <nathanmcmillan54@gmail.com>"]
edition = "2021"

[dependencies]
init = { path = "../../init/" }
libost = { path = "../../lib/libost/" }
