[package]
name = "os"
version = "0.1.0"
authors = ["NathanMcMillan54 <nathanmcmillan54@gmail.com>"]
edition = "2018"

[dependencies]
arch = { path = "../arch/" }
include = { path = "../include/" }
novusk_lib = { path = "../lib/" }