[package]
name = "drivers"
version = "0.1.0"
authors = ["NathanMcMillan <nathanmcmillan54@gmail.com>"]
edition = "2018"


[dependencies]
kernel = { path = "../kernel/" }
spin = "0.5.2"
volatile = "0.2.6"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]
