[package]
name = "userspace"
version = "0.1.0"
authors = ["Nathan McMillan"]
edition = "2018"

[dependencies]
libefi = { path = "../../lib/libefi" }
libnu = "0.1.1"
printk = { path = "../../kernel/printk/" }
