[package]
name = "rpi"
version = "0.1.0"
edition = "2021"
description = "Setup for RaspberryPi devices"

[lib]
path = "src/lib.rs"
crate-type = ["staticlib"]

[dependencies]
novuskinc = { path = "../../../include/novusk/" }
soc = { path = "../../soc/" }
tock-registers = "0.7.0"

[build-dependencies]
difi = { path = "../../../tools/build/difi/" }
