[package]
name = "aarch64"
version = "0.1.0"
authors = ["Nathan McMillan <nathanmcmillan54@gmail.com>"]
edition = "2018"

[workspace]
members = [
    "rpi3/",
]

[dependencies]
# Dependencies
arm = { path = "../arm/" }
uefi = "0.8.0"
uefi-macros = "0.3.3"
uefi-services = "0.5.0"
# Boards
rpi3 = { path = "rpi3/" }
# Drivers
led = { path = "../../drivers/firmware/led/" }
uefi_kd = { path = "../../drivers/uefi_kd/" }
# Include
novusk = { path = "../../include/novusk/" }
# Kernel
init = { path = "../../init/" }
kerror = { path = "../../kernel/kerror/" }
kinfo = { path = "../../kernel/kinfo/" }
# Modules
armm = { path = "../../kernel/modules/armm/" }
# Feature
register = { version = "1.x.x", optional = true }

# Board
[features]
default = []
# Boards/Microcomputers
board_virt = ["register"]
board_rpi3 = ["register"]
# Computers
uefi_rpi3 = ["register"]
