[package]
name = "aarch64"
version = "0.1.0"
authors = ["NathanMcMillan54 <nathanmcmillan54@gmail.com>"]
edition = "2018"

[dependencies]
arm = { path = "../arm/" }
spin = "0.5.2"

[dependencies.lazy_static]
version = "1.0.0"
features = ["spin_no_std"]
