[package]
name = "aarch64"
version = "0.1.0"
authors = ["Nathan McMillan <nathanmcmillan54@gmail.com>"]
edition = "2018"

[workspace]
members = [
    "rpi3/",
]

[dependencies]
# Dependencies
arm = { path = "../arm/" }
spin = "0.5.2"
uefi = "0.8.0"
uefi-macros = "0.3.3"
# Boards
rpi3 = { path = "rpi3/" }
# Drivers
led = { path = "../../drivers/firmware/led/" }
uefi_kd = { path = "../../drivers/uefi_kd/" }
# Include
novusk = { path = "../../include/novusk/" }
# Kernel
kerror = { path = "../../kernel/kerror/" }
kinfo = { path = "../../kernel/kinfo/" }
init = { path = "../../init/" }
printk = { path = "../../kernel/printk/" }
userspace = { path = "../../kernel/userspace/" }
# Libraries
libn = { path = "../../lib/libn/" }
# Modules
armm = { path = "../../kernel/modules/armm/" }

android = { path = "android/" }

# Feature
register = { version = "1.x.x", optional = true }

[dependencies.lazy_static]
version = "1"
features = ["spin_no_std"]

[dependencies.uefi-services]
version = "0.5.0"
features = ["no_panic_handler"]

# Board
[features]
default = []
# Boards/Microcomputers
board_virt = ["register"]
board_rpi3 = ["register"]
# UEFI Computers
uefi_rpi3 = ["register"]

android_os = ["register"]
