[package]
name = "aarch64"
version = "0.1.0"
edition = "2021"
description = "Aarch64/arm64 kernel support"

[lib]
name = "aarch64_kernel_lib"
path = "src/lib.rs"
crate-type = ["staticlib"]
edition = "2021"

[[bin]]
name = "aarch64_kernel_bin"
path = "src/main.rs"
edition = "2021"

[dependencies]
kinfo = { path = "../../kernel/kinfo/" }
nmallocator = { path = "../../mm/nmallocator/", features = ["wee_allocator"] }
novusk_syscalls = "0.2.1"
novuskinc = { path = "../../include/novusk/", features = ["library"] }
tock-registers = "0.7.0"
r0 = "1.0.0"
rpi = { path = "../../drivers/rpi/" }
setup = { path = "../../kernel/setup/" }

[features]
qemu_virt = []
