[package]
name = "aarch64"
version = "0.1.0"
edition = "2018"
description = "Aarch64 support for Novusk"

[dependencies]
arm32 = { path = "../arm32/", features = ["aarch64k"] }
libefi = { path = "../../lib/libefi/" }
