[package]
name = "aarch64"
version = "0.1.0"
edition = "2018"
description = "Aarch64/arm64 kernel support"

[dependencies]
armfb = { path = "../../drivers/gpu/armfb/" }
init = { path = "../../init/" }
kinfo = { path = "../../kernel/kinfo/" }
nmallocator = { path = "../../mm/nmallocator/", features = ["wee_allocator"] }
novuskinc = { path = "../../include/novusk/" }
setup = { path = "../../kernel/setup/" }
tock-registers = "0.7.0"
r0 = "1.0.0"
rpi = { path = "../../drivers/rpi/" }

[features]
rpi3 = ["rpi/rpi3"]
qemu_virt = []
