[package]
name = "gop"
version = "0.1.0"
authors = ["Nathan McMillan <nathanmcmillan54@gmail.com"]
edition = "2018"
description = "A GPU driver for UEFI Novusk"

[dependencies]
uefi = "0.8.1"
# Kernel
kinfo = { path = "../../kernel/kinfo/" }
