[package]
name = "gop"
version = "0.1.0"
edition = "2018"
description = "Graphics Output Protocall, GPU driver for UEFI kernel"

[dependencies]
nkuefi = { path = "../../drivers/nkuefi/" }
macros = { path = "../../kernel/macros/" }
uefi = "0.8.1"
