[package]
name = "hifived"
version = "0.1.0"
edition = "2018"
description = "Hifive/Sifive board setup"

[dependencies]
device = { path = "../../device/" }
hifive1 = { version = "0.10.0", features = ["board-hifive1"] }
novuskinc = { path = "../../../../include/novusk/" }
